services:
  app:
    build:
      target: develop
      cache_from:
        - ghcr.io/${REPOSITORY:-dev-hato/misskey-abuse-user-report-notifier}/app-dev:${TAG_NAME:-latest}
        - ghcr.io/${REPOSITORY:-dev-hato/misskey-abuse-user-report-notifier}/app-dev
    image: ghcr.io/${REPOSITORY:-dev-hato/misskey-abuse-user-report-notifier}/app-dev:${TAG_NAME:-latest}
  db:
    build:
      context: db
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
      cache_from:
        - ghcr.io/${REPOSITORY:-dev-hato/misskey-abuse-user-report-notifier}/db-dev:${TAG_NAME:-latest}
        - ghcr.io/${REPOSITORY:-dev-hato/misskey-abuse-user-report-notifier}/db-dev
    image: ghcr.io/${REPOSITORY:-dev-hato/misskey-abuse-user-report-notifier}/db-dev:${TAG_NAME:-latest}
    env_file:
      - .env
