services:
  app:
    build:
      context: .
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
      cache_from:
        - ghcr.io/${REPOSITORY:-dev-hato/misskey-abuse-user-report-notifier}/app:${TAG_NAME:-latest}
        - ghcr.io/${REPOSITORY:-dev-hato/misskey-abuse-user-report-notifier}/app
    image: ghcr.io/${REPOSITORY:-dev-hato/misskey-abuse-user-report-notifier}/app:${TAG_NAME:-latest}
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
  # Docker以外のDBに接続する場合は以下コメントアウト
  db:
    build:
      context: db
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
      cache_from:
        - ghcr.io/${REPOSITORY:-dev-hato/misskey-abuse-user-report-notifier}/db:${TAG_NAME:-latest}
        - ghcr.io/${REPOSITORY:-dev-hato/misskey-abuse-user-report-notifier}/db
    image: ghcr.io/${REPOSITORY:-dev-hato/misskey-abuse-user-report-notifier}/db:${TAG_NAME:-latest}
    env_file:
      - .env
