// Code generated by ent, DO NOT EDIT.
// @generated

package runtime

// The schema-stitching logic is generated in github.com/dev-hato/misskey-abuse-user-report-notifier/ent/runtime.go

const (
	Version = "v0.13.0"                                         // Version of ent codegen.
	Sum     = "h1:DclxWczaCpyiKn6ZWVcJjq1zIKtJ11iNKy+08lNYsJE=" // Sum of ent codegen.
)
