// Code generated by ent, DO NOT EDIT.
// @generated

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// UserReportsColumns holds the columns for the "user_reports" table.
	UserReportsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
	}
	// UserReportsTable holds the schema information for the "user_reports" table.
	UserReportsTable = &schema.Table{
		Name:       "user_reports",
		Columns:    UserReportsColumns,
		PrimaryKey: []*schema.Column{UserReportsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		UserReportsTable,
	}
)

func init() {
}
