// Code generated by ent, DO NOT EDIT.
// @generated

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dev-hato/misskey-abuse-user-report-notifier/ent/predicate"
	"github.com/dev-hato/misskey-abuse-user-report-notifier/ent/userreport"
)

// UserReportUpdate is the builder for updating UserReport entities.
type UserReportUpdate struct {
	config
	hooks    []Hook
	mutation *UserReportMutation
}

// Where appends a list predicates to the UserReportUpdate builder.
func (uru *UserReportUpdate) Where(ps ...predicate.UserReport) *UserReportUpdate {
	uru.mutation.Where(ps...)
	return uru
}

// Mutation returns the UserReportMutation object of the builder.
func (uru *UserReportUpdate) Mutation() *UserReportMutation {
	return uru.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (uru *UserReportUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, uru.sqlSave, uru.mutation, uru.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uru *UserReportUpdate) SaveX(ctx context.Context) int {
	affected, err := uru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (uru *UserReportUpdate) Exec(ctx context.Context) error {
	_, err := uru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uru *UserReportUpdate) ExecX(ctx context.Context) {
	if err := uru.Exec(ctx); err != nil {
		panic(err)
	}
}

func (uru *UserReportUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(userreport.Table, userreport.Columns, sqlgraph.NewFieldSpec(userreport.FieldID, field.TypeString))
	if ps := uru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if n, err = sqlgraph.UpdateNodes(ctx, uru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userreport.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	uru.mutation.done = true
	return n, nil
}

// UserReportUpdateOne is the builder for updating a single UserReport entity.
type UserReportUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserReportMutation
}

// Mutation returns the UserReportMutation object of the builder.
func (uruo *UserReportUpdateOne) Mutation() *UserReportMutation {
	return uruo.mutation
}

// Where appends a list predicates to the UserReportUpdate builder.
func (uruo *UserReportUpdateOne) Where(ps ...predicate.UserReport) *UserReportUpdateOne {
	uruo.mutation.Where(ps...)
	return uruo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (uruo *UserReportUpdateOne) Select(field string, fields ...string) *UserReportUpdateOne {
	uruo.fields = append([]string{field}, fields...)
	return uruo
}

// Save executes the query and returns the updated UserReport entity.
func (uruo *UserReportUpdateOne) Save(ctx context.Context) (*UserReport, error) {
	return withHooks(ctx, uruo.sqlSave, uruo.mutation, uruo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uruo *UserReportUpdateOne) SaveX(ctx context.Context) *UserReport {
	node, err := uruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (uruo *UserReportUpdateOne) Exec(ctx context.Context) error {
	_, err := uruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uruo *UserReportUpdateOne) ExecX(ctx context.Context) {
	if err := uruo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (uruo *UserReportUpdateOne) sqlSave(ctx context.Context) (_node *UserReport, err error) {
	_spec := sqlgraph.NewUpdateSpec(userreport.Table, userreport.Columns, sqlgraph.NewFieldSpec(userreport.FieldID, field.TypeString))
	id, ok := uruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserReport.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := uruo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userreport.FieldID)
		for _, f := range fields {
			if !userreport.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != userreport.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := uruo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	_node = &UserReport{config: uruo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, uruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userreport.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	uruo.mutation.done = true
	return _node, nil
}
