---
name: super-linter
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  merge_group:
  workflow_dispatch:
permissions:
  contents: read
  packages: read
  statuses: write
jobs:
  super-linter:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4.1.2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4.0.2
        with:
          cache: npm
      - run: |
          npm ci
          action="$(yq '.jobs.super-linter.steps[-1].uses' .github/workflows/super-linter.yml)"
          PATH="$(docker run --rm --entrypoint '' "ghcr.io/${action//\/slim@/:slim-}" /bin/sh -c 'echo $PATH')"
          echo "PATH=/github/workspace/node_modules/.bin:${PATH}" >> "$GITHUB_ENV"
      - name: Super-Linter
        uses: super-linter/super-linter/slim@v6.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main
          LINTER_RULES_PATH: .
          VALIDATE_GO: false
          VALIDATE_JSCPD: false
          IGNORE_GENERATED_FILES: true
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true
