// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// UserReport is the predicate function for userreport builders.
type UserReport func(*sql.Selector)
